/* Part 1*/

--Q1
-- CREATE EMPLOYEES TABLE
create table EMPLOYEES 
( Emp# NUMBER(5),
Lastname varchar2(12),
Firstname varchar2(12),
Job_class varchar2(4)
);

--DESCRIBE THE TABLE
DESC employees;

--Q2
-- ADD NEW COLUMNS
ALTER TABLE EMPLOYEES
ADD (EmpDate DATE DEFAULT SYSDATE,EndDate DATE);

--Q3
--MODIFYING JOB_CLASS COLUMN
ALTER TABLE EMPLOYEES
MODIFY Job_class VARCHAR2(2);

--Q4
--DROP ENDDATE COLUMN
ALTER TABLE EMPLOYEES
DROP COLUMN EndDate;

--Q5
--CREATE JL_EMPS TABLE
CREATE TABLE JL_EMPS AS
(SELECT Emp#, Lastname, Firstname from EMPLOYEES);

DESC jl_emps;

--Q6
--TRUNCATE THE JL_EMPS TABLE
TRUNCATE TABLE JL_EMPS;

--Q7
--DROPPING THE TABLE USING PURGE
DROP TABLE JL_EMPS PURGE;

--Q8
--DROP EMPLOYEES TABLE
DROP TABLE EMPLOYEES;

--RECOVER EMPLOYEES TABLE
FLASHBACK TABLE EMPLOYEES
TO BEFORE DROP;


SELECT * FROM EMPLOYEES;




/* PART III*/

/* CREATING TABLES DEPT, EQUIP AND ETYPES FOR TESTING*/
CREATE TABLE DEPT
(DEPTID VARCHAR2(10) PRIMARY KEY,
DNAME VARCHAR2(10),
FAX VARCHAR2(10));

CREATE TABLE ETYPES
(ETYPEID VARCHAR2(10) PRIMARY KEY,
ETYPENAME VARCHAR2(10));

CREATE TABLE EQUIP(
EQUIPID VARCHAR2(10) PRIMARY KEY,
EDESC VARCHAR2(10),
PURCHDATE DATE,
RATING VARCHAR2(4),
DEPTID VARCHAR2(10),
ETYPEID VARCHAR2(10));

--Constraint 1

ALTER TABLE DEPT
ADD CONSTRAINT DEPT_NAME_UK UNIQUE (Dname);

--Constraint 2

ALTER TABLE DEPT
MODIFY (Dname CONSTRAINT dept_name_nn NOT NULL);

--Constraint 3

ALTER TABLE ETYPES
ADD CONSTRAINT ETYPES_NAME_UK UNIQUE (Etypename);

--Constraint 4

ALTER TABLE ETYPES
MODIFY (Etypename CONSTRAINT Etype_name_nn NOT NULL);

--Constraint 5

ALTER TABLE EQUIP
ADD CONSTRAINT EQUIP_DEPT_FK FOREIGN KEY (DeptID)
REFERENCES DEPT (DeptID);

--Constraint 6

ALTER TABLE EQUIP
ADD CONSTRAINT EQUIP_TYPE_FK FOREIGN KEY (EtypeID)
REFERENCES ETYPES (EtypeID);

--Constraint 7

ALTER TABLE EQUIP
ADD CONSTRAINT EQUIP_RATING_CHK CHECK (Rating in ('A','B','C'));

--QUERY TO VERIFY CONSTRAINTS
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='EQUIP';

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='DEPT';

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='ETYPES';
